apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
  labels:
    type: local
spec:
  storageClassName: influxdb
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume-claim
spec:
  storageClassName: influxdb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - name: influxdb-port
      protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb_image
        ports:
        - containerPort: 8086
        imagePullPolicy: Never
        volumeMounts:
        - name: influxdb-volume
          mountPath: /var/lib/influxdb
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-volume-claim
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock