apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.165
  ports:
    - name: ftps-port
      protocol: TCP
      port: 21
      targetPort: 21
    - port: 10100
      name: port-passv
      protocol: TCP
      targetPort: 10100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        ports:
        - containerPort: 21
        - containerPort: 10100
        imagePullPolicy: Never